create extension if not exists pgcrypto;

create table if not exists audit_logs (
  id uuid primary key default gen_random_uuid(),
  admin_id uuid,
  action_type text not null,
  timestamp timestamptz not null default now()
);

create table if not exists admins (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text not null unique,
  password_hash text not null,
  role text not null check (role in ('adminprime', 'subadmin')),
  created_by uuid,
  created_at timestamptz not null default now()
);

create table if not exists secret_keys (
  id uuid primary key default gen_random_uuid(),
  key text not null unique check (key like 'starlabs-%'),
  assigned_name text not null,
  assigned_whatsapp text not null,
  assigned_email text not null,
  used boolean not null default false,
  used_at timestamptz,
  created_by uuid,
  created_at timestamptz not null default now()
);

create table if not exists premium_users (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  whatsapp text not null,
  email text not null,
  secret_key_id uuid references secret_keys(id),
  created_at timestamptz not null default now()
);

create table if not exists course_content (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  category text not null,
  body text not null,
  created_by uuid,
  created_at timestamptz not null default now()
);

-- Replace the password hash with one generated by PHP password_hash().
insert into admins (id, name, email, password_hash, role)
values (
  '00000000-0000-0000-0000-000000000001',
  'Admin Prime',
  'adminprime@example.com',
  '$2y$10$replaceWithARealPasswordHashGeneratedByPHP',
  'adminprime'
)
on conflict (id) do nothing;
